import type {
  EarthID,
  Conversation,
  ConversationMember,
  ConversationSpace,
  Message,
  TrustRelationship,
  ConsentMatrix,
  SafetyPolicy,
  LedgerEvent,
  MessageAction,
} from './types';

// ─── Mock EarthIDs ────────────────────────────────────────────────────────────

export const MOCK_EARTH_IDS: EarthID[] = [
  {
    id: 'eid-001',
    authUserId: 'auth-001',
    handle: '@river.nova',
    displayName: 'River Nova',
    avatarUrl: 'https://images.pexels.com/photos/1987301/pexels-photo-1987301.jpeg?w=150',
    bio: 'Steward of living systems. Earth Collective Exchange contributor.',
    sovereignSince: '2024-01-15T08:00:00Z',
    isActive: true,
    storagePreference: 'encrypted_relay',
    intentionMirrorConfig: {
      enabled: true,
      checkBeforeSending: true,
      toneReflection: true,
      harmfulPatternWarning: true,
      userCanOverride: true,
      reflectionMode: 'soft',
    },
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-03-10T14:22:00Z',
    isLocal: false,
  },
  {
    id: 'eid-002',
    authUserId: 'auth-002',
    handle: '@cedar.light',
    displayName: 'Cedar Light',
    avatarUrl: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=150',
    bio: 'Community architect. Council facilitator.',
    sovereignSince: '2024-02-03T10:30:00Z',
    isActive: true,
    storagePreference: 'encrypted_backup',
    intentionMirrorConfig: {
      enabled: true,
      checkBeforeSending: true,
      toneReflection: true,
      harmfulPatternWarning: false,
      userCanOverride: true,
      reflectionMode: 'clear',
    },
    createdAt: '2024-02-03T10:30:00Z',
    updatedAt: '2024-04-01T09:00:00Z',
    isLocal: false,
  },
  {
    id: 'eid-003',
    authUserId: 'auth-003',
    handle: '@sol.kepler',
    displayName: 'Sol Kepler',
    avatarUrl: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?w=150',
    bio: 'Regenerative finance. EarthCoin future contributor.',
    sovereignSince: '2024-03-20T16:00:00Z',
    isActive: true,
    storagePreference: 'local_only',
    intentionMirrorConfig: {
      enabled: false,
      checkBeforeSending: false,
      toneReflection: false,
      harmfulPatternWarning: false,
      userCanOverride: true,
      reflectionMode: 'soft',
    },
    createdAt: '2024-03-20T16:00:00Z',
    updatedAt: '2024-03-20T16:00:00Z',
    isLocal: false,
  },
  {
    id: 'eid-004',
    authUserId: 'auth-004',
    handle: '@moss.garden',
    displayName: 'Moss Garden',
    bio: 'Place steward — Forest Sanctuary Project.',
    sovereignSince: '2024-04-01T11:00:00Z',
    isActive: true,
    storagePreference: 'encrypted_relay',
    intentionMirrorConfig: {
      enabled: true,
      checkBeforeSending: true,
      toneReflection: true,
      harmfulPatternWarning: true,
      userCanOverride: true,
      reflectionMode: 'strict',
    },
    createdAt: '2024-04-01T11:00:00Z',
    updatedAt: '2024-04-01T11:00:00Z',
    isLocal: false,
  },
];

// ─── Mock Trust Relationships ─────────────────────────────────────────────────

export const MOCK_TRUST_RELATIONSHIPS: TrustRelationship[] = [
  { id: 'tr-001', fromEarthId: 'eid-001', toEarthId: 'eid-002', level: 'trusted', grantedAt: '2024-02-10T00:00:00Z' },
  { id: 'tr-002', fromEarthId: 'eid-002', toEarthId: 'eid-001', level: 'trusted', grantedAt: '2024-02-10T00:00:00Z' },
  { id: 'tr-003', fromEarthId: 'eid-001', toEarthId: 'eid-003', level: 'known',   grantedAt: '2024-03-25T00:00:00Z' },
  { id: 'tr-004', fromEarthId: 'eid-003', toEarthId: 'eid-001', level: 'community', grantedAt: '2024-03-25T00:00:00Z' },
  { id: 'tr-005', fromEarthId: 'eid-002', toEarthId: 'eid-004', level: 'known',   grantedAt: '2024-04-05T00:00:00Z' },
  { id: 'tr-006', fromEarthId: 'eid-001', toEarthId: 'eid-004', level: 'community', grantedAt: '2024-04-05T00:00:00Z' },
];

// ─── Mock Consent Matrices ────────────────────────────────────────────────────

export const MOCK_CONSENT_MATRICES: ConsentMatrix[] = [
  {
    id: 'cm-001',
    earthId: 'eid-001',
    allowDirectFrom: ['trusted'],
    requireRequestFrom: ['known', 'community'],
    allowGroupInviteFrom: ['trusted', 'known'],
    allowEventInviteFrom: ['trusted', 'known', 'community'],
    allowProjectInviteFrom: ['trusted', 'known'],
    allowContributionRequestFrom: ['trusted'],
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'cm-002',
    earthId: 'eid-002',
    allowDirectFrom: ['trusted', 'known'],
    requireRequestFrom: ['community'],
    allowGroupInviteFrom: ['trusted', 'known', 'community'],
    allowEventInviteFrom: ['trusted', 'known', 'community'],
    allowProjectInviteFrom: ['trusted', 'known'],
    allowContributionRequestFrom: ['trusted', 'known'],
    updatedAt: '2024-04-01T00:00:00Z',
  },
];

// ─── Mock Safety Policies ─────────────────────────────────────────────────────

export const MOCK_SAFETY_POLICIES: SafetyPolicy[] = [
  {
    id: 'sp-001',
    earthId: 'eid-001',
    blockedEarthIds: [],
    mutedEarthIds: [],
    rateLimitUnknownSenders: true,
    maxMessagesPerHourUnknown: 3,
    maxEmergencySignals: 2,
    reportAbuse: true,
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'sp-002',
    earthId: 'eid-002',
    blockedEarthIds: [],
    mutedEarthIds: [],
    rateLimitUnknownSenders: true,
    maxMessagesPerHourUnknown: 5,
    maxEmergencySignals: 2,
    reportAbuse: true,
    updatedAt: '2024-04-01T00:00:00Z',
  },
];

// ─── Mock Spaces ──────────────────────────────────────────────────────────────

export const MOCK_SPACES: ConversationSpace[] = [
  {
    id: 'space-family',
    name: 'Family',
    description: 'Close family conversations and shared care.',
    icon: '◉',
    accentColor: 'rose',
    category: 'family',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-team',
    name: 'EarthOS Team',
    description: 'Coordination and decisions for the EarthOS core team.',
    icon: '◈',
    accentColor: 'sky',
    category: 'team',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-ceremony',
    name: 'Sacred Gathering',
    description: 'Sacred and ceremonial gathering spaces.',
    icon: '◎',
    accentColor: 'amber',
    category: 'gathering',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-build',
    name: 'World360 Build',
    description: 'Active build coordination for World360 projects.',
    icon: '◆',
    accentColor: 'teal',
    category: 'build',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-artist',
    name: 'Artist',
    description: 'Creative collaborations and expressive work.',
    icon: '◇',
    accentColor: 'amber',
    category: 'artist',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-documents',
    name: 'Legal & Documents',
    description: 'Agreements, documents, and formal records.',
    icon: '▣',
    accentColor: 'slate',
    category: 'documents',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-care',
    name: 'Care Circle',
    description: 'Support, care, and wellbeing conversations.',
    icon: '◍',
    accentColor: 'rose',
    category: 'care',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-community',
    name: 'Community',
    description: 'Open community coordination and shared causes.',
    icon: '⬡',
    accentColor: 'emerald',
    category: 'community',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'space-projects',
    name: 'Projects',
    description: 'Active project workspaces and coordination.',
    icon: '◉',
    accentColor: 'sky',
    category: 'projects',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// ─── Mock Conversations ───────────────────────────────────────────────────────

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-001',
    type: 'direct',
    title: undefined,
    titleKind: 'default',           // no authored title — renderer uses localized type label
    createdByEarthId: 'eid-001',
    storageMode: 'encrypted_relay',
    spaceId: 'space-team',
    isArchived: false,
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2024-04-30T18:45:00Z',
  },
  {
    id: 'conv-002',
    type: 'council',
    title: 'Forest Sanctuary Council',
    titleKind: 'custom',            // user-authored — render verbatim, never re-translate
    titleLocale: 'en',
    description: 'Governance circle for the Forest Sanctuary regeneration project.',
    createdByEarthId: 'eid-002',
    storageMode: 'encrypted_relay',
    spaceId: 'space-community',
    isArchived: false,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-04-29T20:00:00Z',
  },
  {
    id: 'conv-003',
    type: 'project',
    title: 'Earth Collective Exchange — Water Commons',
    titleKind: 'custom',            // user-authored — render verbatim, never re-translate
    titleLocale: 'en',
    description: 'Coordination channel for the Water Commons contribution project.',
    createdByEarthId: 'eid-001',
    storageMode: 'encrypted_backup',
    spaceId: 'space-projects',
    isArchived: false,
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2024-04-30T12:00:00Z',
  },
  {
    id: 'conv-004',
    type: 'support_circle',
    title: 'Transition Support',
    titleKind: 'custom',            // user-authored — render verbatim, never re-translate
    titleLocale: 'en',
    createdByEarthId: 'eid-004',
    storageMode: 'encrypted_relay',
    spaceId: 'space-care',
    isArchived: false,
    createdAt: '2024-04-20T14:00:00Z',
    updatedAt: '2024-04-28T09:00:00Z',
  },
  {
    id: 'conv-005',
    type: 'cause',
    title: 'Seed Library Network',
    titleKind: 'custom',            // user-authored — render verbatim, never re-translate
    titleLocale: 'en',
    description: 'Open coordination space for the Seed Library cause.',
    createdByEarthId: 'eid-003',
    storageMode: 'encrypted_relay',
    spaceId: 'space-community',
    isArchived: false,
    createdAt: '2024-04-15T11:00:00Z',
    updatedAt: '2024-04-27T16:00:00Z',
  },
];

// ─── Mock Conversation Members ────────────────────────────────────────────────

export const MOCK_MEMBERS: ConversationMember[] = [
  { id: 'mem-001', conversationId: 'conv-001', earthId: 'eid-001', role: 'owner', trustSnapshot: 'trusted', joinedAt: '2024-04-10T09:00:00Z' },
  { id: 'mem-002', conversationId: 'conv-001', earthId: 'eid-002', role: 'member', trustSnapshot: 'trusted', joinedAt: '2024-04-10T09:00:00Z' },
  { id: 'mem-003', conversationId: 'conv-002', earthId: 'eid-002', role: 'owner', trustSnapshot: 'self', joinedAt: '2024-03-01T10:00:00Z' },
  { id: 'mem-004', conversationId: 'conv-002', earthId: 'eid-001', role: 'member', trustSnapshot: 'trusted', joinedAt: '2024-03-01T10:00:00Z' },
  { id: 'mem-005', conversationId: 'conv-002', earthId: 'eid-004', role: 'member', trustSnapshot: 'known', joinedAt: '2024-03-05T10:00:00Z' },
  { id: 'mem-006', conversationId: 'conv-003', earthId: 'eid-001', role: 'owner', trustSnapshot: 'self', joinedAt: '2024-04-01T08:00:00Z' },
  { id: 'mem-007', conversationId: 'conv-003', earthId: 'eid-003', role: 'member', trustSnapshot: 'known', joinedAt: '2024-04-02T08:00:00Z' },
  { id: 'mem-008', conversationId: 'conv-005', earthId: 'eid-003', role: 'owner', trustSnapshot: 'self', joinedAt: '2024-04-15T11:00:00Z' },
  { id: 'mem-009', conversationId: 'conv-005', earthId: 'eid-001', role: 'member', trustSnapshot: 'known', joinedAt: '2024-04-16T09:00:00Z' },
];

// ─── Mock Messages ────────────────────────────────────────────────────────────

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-001',
    conversationId: 'conv-001',
    senderId: 'eid-001',
    type: 'text',
    body: 'Cedar — the Water Commons proposal is ready for your review.',
    consentStatus: 'allowed',
    storageMode: 'encrypted_relay',
    trustLevel: 'trusted',
    actionState: 'none',
    intentionMirrorState: 'clear',
    integrityHash: 'hash::cmV2aWV3X3JlcXVlc3RfMDAx',
    isDeleted: false,
    createdAt: '2024-04-30T09:12:00Z',
    createdLocale: 'en',
    contentKind: 'demo',
  },
  {
    id: 'msg-002',
    conversationId: 'conv-001',
    senderId: 'eid-002',
    type: 'text',
    body: 'Thank you, I will read it today. Can we meet in the council space?',
    consentStatus: 'allowed',
    storageMode: 'encrypted_relay',
    trustLevel: 'trusted',
    actionState: 'none',
    intentionMirrorState: 'not_checked',
    integrityHash: 'hash::cmVwbHlfMDAy',
    isDeleted: false,
    createdAt: '2024-04-30T10:03:00Z',
    createdLocale: 'en',
    contentKind: 'demo',
  },
  {
    id: 'msg-003',
    conversationId: 'conv-002',
    senderId: 'eid-002',
    type: 'proposal',
    body: 'Proposal: Forest Sanctuary — expand the protected water corridor by 3 hectares.',
    consentStatus: 'allowed',
    storageMode: 'encrypted_relay',
    trustLevel: 'self',
    actionState: 'agreement',
    intentionMirrorState: 'clear',
    integrityHash: 'hash::cHJvcG9zYWxfMDAz',
    isDeleted: false,
    createdAt: '2024-04-29T15:00:00Z',
    createdLocale: 'en',
    contentKind: 'demo',
  },
  {
    id: 'msg-004',
    conversationId: 'conv-003',
    senderId: 'eid-003',
    type: 'task',
    body: 'Task: Complete baseline water-quality survey by May 15.',
    consentStatus: 'allowed',
    storageMode: 'encrypted_backup',
    trustLevel: 'known',
    actionState: 'task',
    intentionMirrorState: 'clear',
    integrityHash: 'hash::dGFza18wMDQ=',
    isDeleted: false,
    createdAt: '2024-04-28T11:30:00Z',
    createdLocale: 'en',
    contentKind: 'demo',
  },
  {
    id: 'msg-005',
    conversationId: 'conv-001',
    senderId: 'eid-001',
    type: 'text',
    body: 'I need this done now — everyone always misses deadlines.',
    consentStatus: 'allowed',
    storageMode: 'encrypted_relay',
    trustLevel: 'trusted',
    actionState: 'none',
    intentionMirrorState: 'user_overrode',
    integrityHash: 'hash::b3ZlcnJpZGVfMDA1',
    isDeleted: false,
    createdAt: '2024-04-28T17:45:00Z',
    createdLocale: 'en',
    contentKind: 'demo',
  },
];

// ─── Mock Message Actions ─────────────────────────────────────────────────────

export const MOCK_MESSAGE_ACTIONS: MessageAction[] = [
  {
    id: 'ma-001',
    messageId: 'msg-003',
    conversationId: 'conv-002',
    initiatedByEarthId: 'eid-002',
    actionType: 'agreement',
    status: 'open',
    payload: { proposalTitle: 'Forest Sanctuary Water Corridor Expansion' },
    createdAt: '2024-04-29T15:00:00Z',
  },
  {
    id: 'ma-002',
    messageId: 'msg-004',
    conversationId: 'conv-003',
    initiatedByEarthId: 'eid-003',
    actionType: 'task',
    status: 'open',
    payload: { taskName: 'Water Quality Survey', assignedTo: 'eid-001' },
    dueAt: '2024-05-15T00:00:00Z',
    createdAt: '2024-04-28T11:30:00Z',
  },
];

// ─── Mock Ledger Events — Full Six-Validation Lifecycle ───────────────────────

export const MOCK_LEDGER_EVENTS: LedgerEvent[] = [
  {
    id: 'le-001',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-001',
    eventType: 'trust_checked',
    passed: true,
    detail: 'Trust level: trusted. Direct message allowed.',
    createdAt: '2024-04-30T09:11:59Z',
  },
  {
    id: 'le-002',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-001',
    eventType: 'consent_validated',
    passed: true,
    detail: 'Consent granted: trusted senders allowed direct messages.',
    createdAt: '2024-04-30T09:11:59Z',
  },
  {
    id: 'le-003',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-001',
    eventType: 'safety_checked',
    passed: true,
    detail: 'Sender not in block or mute list.',
    createdAt: '2024-04-30T09:11:59Z',
  },
  {
    id: 'le-004',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-001',
    eventType: 'rate_limit_checked',
    passed: true,
    detail: 'Trusted sender — rate limit not applied.',
    createdAt: '2024-04-30T09:11:59Z',
  },
  {
    id: 'le-005',
    earthId: 'eid-001',
    conversationId: 'conv-001',
    messageId: 'msg-001',
    eventType: 'storage_validated',
    passed: true,
    detail: 'Resolved storage mode: encrypted_relay.',
    createdAt: '2024-04-30T09:11:59Z',
  },
  {
    id: 'le-006',
    earthId: 'eid-001',
    conversationId: 'conv-001',
    messageId: 'msg-001',
    eventType: 'message_created',
    passed: true,
    detail: "Message of type 'text' created with storage mode 'encrypted_relay'.",
    createdAt: '2024-04-30T09:12:00Z',
  },
  // Mirror override event for msg-005
  {
    id: 'le-007',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-005',
    eventType: 'mirror_reflected',
    passed: true,
    detail: 'Absolute language may close dialogue. | High punctuation intensity detected.',
    createdAt: '2024-04-28T17:44:55Z',
  },
  {
    id: 'le-008',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-005',
    eventType: 'mirror_overrode',
    passed: true,
    detail: 'User acknowledged reflection and chose to send.',
    createdAt: '2024-04-28T17:44:58Z',
  },
  {
    id: 'le-009',
    earthId: 'eid-001',
    relatedEarthId: 'eid-002',
    conversationId: 'conv-001',
    messageId: 'msg-005',
    eventType: 'message_created',
    passed: true,
    detail: "Message of type 'text' created with storage mode 'encrypted_relay'. Mirror state: user_overrode.",
    createdAt: '2024-04-28T17:45:00Z',
  },
];
