/**
 * QLPA Application Constants
 * Stable identifiers, storage keys, version markers.
 * Import from here rather than hardcoding strings throughout the app.
 *
 * Host app customization: override DEFAULT_APP_NAME and STORAGE_NAMESPACE
 * in your own app layer — do not edit this file directly.
 */

// Host apps should override this in their own layer (e.g. APP_NAME = 'My App').
export const DEFAULT_APP_NAME = 'QLPA Matrix Source';
export const APP_VERSION = '0.1.0';
export const APP_MATURITY = 'local-first prototype';

// Host apps should replace this namespace string to avoid storage key collisions.
export const STORAGE_NAMESPACE = 'qlpa';

export const STORAGE_KEYS = {
  locale:               `${STORAGE_NAMESPACE}.locale`,
  humanMode:            `${STORAGE_NAMESPACE}.human_mode`,
  interfaceDepth:       `${STORAGE_NAMESPACE}.interface_depth`,
  appMode:              `${STORAGE_NAMESPACE}.app_mode`,
  statsMode:            `${STORAGE_NAMESPACE}.stats_mode`,
  backgroundMode:       `${STORAGE_NAMESPACE}.background_mode`,
  reducedMotion:        `${STORAGE_NAMESPACE}.reduced_motion`,
  compactMode:          `${STORAGE_NAMESPACE}.compact_mode`,
  developerDiagnostics: `${STORAGE_NAMESPACE}.developer_diagnostics`,
  localStore:           `${STORAGE_NAMESPACE}.local_store`,
  viewLevel:            `${STORAGE_NAMESPACE}.view_level`, // legacy key — migrate on read
} as const;

// Technical terms that are stable across all locales — do not translate
export const STABLE_TECHNICAL_TERMS = [
  'EarthOS',
  'EarthID',
  'QLPA',
  'AES-GCM-256',
  'AES-GCM',
  'MVP',
  'QA',
] as const;

// Rate limits (mirrors safety.ts logic)
export const RATE_LIMITS = {
  maxMessagesPerHourUnknown: 3,
  maxEmergencySignalsPerDay: 2,
} as const;

// Default preferences
export const PREFERENCE_DEFAULTS = {
  locale:               'en',
  humanMode:            'calm',
  interfaceDepth:       'simple',
  appMode:              'local_first',
  statsMode:            'light',
  backgroundMode:       'earth_alive',
  reducedMotion:        false,
  compactMode:          false,
  developerDiagnostics: false,
} as const;
